#!/usr/bin/env zsh

# Set the folders to stow
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="alacritty,gitconfig,i3,nvim,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES #$DOTFILES/install

echo "dotfiles folder: $DOTFILES"
echo "stowing folders: $STOW_FOLDERS\n"

pushd $DOTIFLES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow --dir $DOTFILES -D $folder
    stow --dir $DOTFILES $folder
done
popd

